import { proxyImageUrl } from "@/lib/image-proxy";
import {
  getAliasPackageDisplayName,
  resolvePlayPackageIdAlias,
} from "@/lib/search-aliases";

/** Apps that gplay.app() often cannot fetch; search still returns a verifiable package id. */
export type CuratedSearchAppMeta = {
  appId: string;
  title: string;
  summary: string;
  developer: string;
  developerId: string;
  iconUrl: string;
  playUrl: string;
};

const CURATED_BY_APP_ID: Readonly<Record<string, CuratedSearchAppMeta>> = {
  "com.android.vending": {
    appId: "com.android.vending",
    title: "Google Play Store",
    summary: "Official Android app store to browse, install, and update apps and games.",
    developer: "Google LLC",
    developerId: "Google+LLC",
    iconUrl:
      "https://play-lh.googleusercontent.com/kSsoniKnHcxnPAhTyiSRJXrRhANxnmXnCNk0ZnZ3AY4=w240-h480-rw",
    playUrl: "https://play.google.com/store/apps/details?id=com.android.vending",
  },
  "atws.app": {
    appId: "atws.app",
    title: "IBKR Mobile",
    summary: "Interactive Brokers mobile trading app.",
    developer: "Interactive Brokers",
    developerId: "Interactive+Brokers",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=atws.app",
  },
  "com.tigerbrokers.stock": {
    appId: "com.tigerbrokers.stock",
    title: "Tiger Trade",
    summary: "Tiger Brokers stock trading app for global markets.",
    developer: "Tiger Brokers",
    developerId: "Tiger+Brokers",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.tigerbrokers.stock",
  },
  "cn.futu.trader": {
    appId: "cn.futu.trader",
    title: "Futubull",
    summary: "Futu / Futubull trading app.",
    developer: "Futu Holdings",
    developerId: "Futu+Holdings",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=cn.futu.trader",
  },
  "global.longbridge.app.android": {
    appId: "global.longbridge.app.android",
    title: "Longbridge",
    summary: "Longbridge Securities trading app.",
    developer: "Longbridge Securities",
    developerId: "Longbridge+Securities",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=global.longbridge.app.android",
  },
  "com.moomoo.trade": {
    appId: "com.moomoo.trade",
    title: "moomoo",
    summary: "Moomoo trading platform.",
    developer: "Moomoo Inc.",
    developerId: "Moomoo+Inc.",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.moomoo.trade",
  },
  "com.grindrapp.android": {
    appId: "com.grindrapp.android",
    title: "Grindr",
    summary: "Social networking app for the LGBTQ+ community.",
    developer: "Grindr LLC",
    developerId: "Grindr+LLC",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.grindrapp.android",
  },
  "org.localsend.localsend_app": {
    appId: "org.localsend.localsend_app",
    title: "LocalSend",
    summary: "Share files to nearby devices on your local network.",
    developer: "Tien Do Nam",
    developerId: "Tien+Do+Nam",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=org.localsend.localsend_app",
  },
  "com.wx.freecine": {
    appId: "com.wx.freecine",
    title: "Freecine Filmes e Séries",
    summary: "Lightweight video player for your own media files.",
    developer: "Walpapers zero",
    developerId: "Walpapers+zero",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.wx.freecine",
  },
  "com.cinefffflix.com": {
    appId: "com.cinefffflix.com",
    title: "CINE TV",
    summary: "Media player for high-quality video playback.",
    developer: "Heinsenberg Dev",
    developerId: "Heinsenberg+Dev",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.cinefffflix.com",
  },
  "com.bkash.customerapp": {
    appId: "com.bkash.customerapp",
    title: "bKash",
    summary: "Mobile financial services app for Bangladesh.",
    developer: "bKash Limited",
    developerId: "bKash+Limited",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.bkash.customerapp",
  },
  "com.winlator": {
    appId: "com.winlator",
    title: "Winlator",
    summary: "Run Windows games and apps on Android via Wine/Box64.",
    developer: "Winlator",
    developerId: "Winlator",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.winlator",
  },
  "io.github.romanvht.byedpi": {
    appId: "io.github.romanvht.byedpi",
    title: "ByeByeDPI",
    summary: "Local DPI bypass tool for Android (open-source fork).",
    developer: "romanvht",
    developerId: "romanvht",
    iconUrl: "",
    playUrl: "https://github.com/romanvht/ByeByeDPI",
  },
  "com.truecaller": {
    appId: "com.truecaller",
    title: "Truecaller",
    summary: "Caller ID, spam blocking, and messaging.",
    developer: "Truecaller International LLP",
    developerId: "Truecaller+International+LLP",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.truecaller",
  },
  "com.snapchat.android": {
    appId: "com.snapchat.android",
    title: "Snapchat",
    summary: "Share moments with friends through photos and videos.",
    developer: "Snap Inc",
    developerId: "Snap+Inc",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.snapchat.android",
  },
  "com.animohub.pro": {
    appId: "com.animohub.pro",
    title: "AnimoHub",
    summary: "Anime and entertainment streaming app.",
    developer: "AnimoHub",
    developerId: "AnimoHub",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.animohub.pro",
  },
  "com.globe.gcash.android": {
    appId: "com.globe.gcash.android",
    title: "GCash",
    summary: "Philippines mobile wallet — send money, pay bills, scan QR.",
    developer: "Mynt - Globe Fintech Innovations, Inc.",
    developerId: "Mynt+-+Globe+Fintech+Innovations,+Inc.",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.globe.gcash.android",
  },
  "com.mojang.minecraftpreview": {
    appId: "com.mojang.minecraftpreview",
    title: "Minecraft Preview",
    summary: "Official Minecraft beta/preview builds for Android.",
    developer: "Mojang",
    developerId: "Mojang",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.mojang.minecraftpreview",
  },
  "com.scee.psx.android": {
    appId: "com.scee.psx.android",
    title: "PlayStation App",
    summary: "Connect to your PlayStation console and manage games.",
    developer: "PlayStation Mobile Inc.",
    developerId: "PlayStation+Mobile+Inc.",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.scee.psx.android",
  },
  "com.teamspeak.ts3client": {
    appId: "com.teamspeak.ts3client",
    title: "TeamSpeak 3",
    summary: "Voice chat for gaming and teams.",
    developer: "TeamSpeak Systems GmbH",
    developerId: "TeamSpeak+Systems+GmbH",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.teamspeak.ts3client",
  },
  "com.asxkkc.jbz": {
    appId: "com.asxkkc.jbz",
    title: "星影视频",
    summary: "Free video streaming app.",
    developer: "",
    developerId: "",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.asxkkc.jbz",
  },
  "com.dragon.read": {
    appId: "com.dragon.read",
    title: "番茄免费小说",
    summary: "字节跳动旗下免费小说阅读应用，海量正版小说免费读。",
    developer: "北京臻鼎科技有限公司",
    developerId: "北京臻鼎科技有限公司",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.dragon.read",
  },
  "com.dragon.read.oversea.gp": {
    appId: "com.dragon.read.oversea.gp",
    title: "番茄免费小说",
    summary: "Free novel reading app by ByteDance.",
    developer: "Beijing Zhending Technology Co., Ltd.",
    developerId: "Beijing+Zhending+Technology+Co.+Ltd.",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.dragon.read.oversea.gp",
  },
  "com.biyaglobal.www": {
    appId: "com.BIYAGlobal.www",
    title: "BiyaPay",
    summary: "Cross-border payment and digital wallet app.",
    developer: "BIYA Global",
    developerId: "BIYA+Global",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.BIYAGlobal.www",
  },
  "org.readera": {
    appId: "org.readera",
    title: "ReadEra",
    summary: "Read books and documents for free without ads.",
    developer: "READERA LLC",
    developerId: "READERA+LLC",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=org.readera",
  },
  "com.minitech.miniworld": {
    appId: "com.minitech.miniworld",
    title: "迷你世界",
    summary: "Sandbox creative game popular in China.",
    developer: "Miniwan Technology",
    developerId: "Miniwan+Technology",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.minitech.miniworld",
  },
  "com.fds.infiniteflight": {
    appId: "com.fds.infiniteflight",
    title: "Infinite Flight",
    summary: "Mobile flight simulator with global scenery.",
    developer: "Infinite Flight LLC",
    developerId: "Infinite+Flight+LLC",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.fds.infiniteflight",
  },
  "jp.softether.vpngate": {
    appId: "jp.softether.vpngate",
    title: "VPN Gate Client",
    summary: "SoftEther VPN client for VPN Gate academic relay network.",
    developer: "University of Tsukuba",
    developerId: "University+of+Tsukuba",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=jp.softether.vpngate",
  },
  "com.xarxzht.ybdc.app": {
    appId: "com.xarxzht.ybdc.app",
    title: "易背单词",
    summary: "English vocabulary learning app.",
    developer: "",
    developerId: "",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.xarxzht.ybdc.app",
  },
  "com.vuuu.tinyterraces": {
    appId: "com.VuVuu.TinyTerraces",
    title: "Tiny Terraces",
    summary: "Casual terrace-building puzzle game.",
    developer: "VuVuu",
    developerId: "VuVuu",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.VuVuu.TinyTerraces",
  },
  "com.netease.party": {
    appId: "com.netease.party",
    title: "蛋仔派对",
    summary: "网易派对竞技手游，多人闯关与 UGC 地图。",
    developer: "网易雷火",
    developerId: "网易雷火",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.netease.party",
  },
  "com.grafana.oncall.prod": {
    appId: "com.grafana.oncall.prod",
    title: "Grafana IRM",
    summary: "Grafana Cloud incident response and on-call mobile app.",
    developer: "Grafana Labs",
    developerId: "Grafana+Labs",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.grafana.oncall.prod",
  },
  "com.avast.android.mobilesecurity": {
    appId: "com.avast.android.mobilesecurity",
    title: "Avast Mobile Security",
    summary: "Antivirus, VPN, and privacy protection for Android.",
    developer: "Avast Software",
    developerId: "Avast+Software",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.avast.android.mobilesecurity",
  },
  "com.fusionmedia.investing": {
    appId: "com.fusionmedia.investing",
    title: "Investing.com",
    summary: "Stock quotes, charts, and financial news.",
    developer: "Fusion Media Limited",
    developerId: "Fusion+Media+Limited",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.fusionmedia.investing",
  },
  "com.microsoft.whiteboard.live": {
    appId: "com.microsoft.whiteboard.live",
    title: "Microsoft Whiteboard",
    summary: "Collaborative digital whiteboard.",
    developer: "Microsoft Corporation",
    developerId: "Microsoft+Corporation",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.microsoft.whiteboard.live",
  },
  "com.nintendo.znca": {
    appId: "com.nintendo.znca",
    title: "Fire Emblem Heroes",
    summary: "Nintendo tactical RPG mobile game.",
    developer: "Nintendo Co., Ltd.",
    developerId: "Nintendo+Co.+Ltd.",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.nintendo.znca",
  },
  "com.musicgpt.app.android": {
    appId: "com.musicgpt.app.android",
    title: "MusicGPT",
    summary: "AI song generator with lyrics and vocals.",
    developer: "MusicGPT",
    developerId: "MusicGPT",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.musicgpt.app.android",
  },
  "in.thebase.base": {
    appId: "in.thebase.base",
    title: "Pay ID",
    summary: "Shopping app for BASE online stores.",
    developer: "BASE, Inc.",
    developerId: "BASE+Inc.",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=in.thebase.base",
  },
  "cloud.hosenso.maui": {
    appId: "cloud.hosenso.maui",
    title: "Hosenso",
    summary: "Smart home and energy management companion app.",
    developer: "Hosenso GmbH",
    developerId: "Hosenso+GmbH",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=cloud.hosenso.maui",
  },
  "com.nebula.karing": {
    appId: "com.nebula.karing",
    title: "Karing",
    summary: "Rule-based network proxy utility for Clash and sing-box.",
    developer: "KaringX",
    developerId: "KaringX",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.nebula.karing",
  },
  "com.ma.polyfield": {
    appId: "com.MA.Polyfield",
    title: "方块战场",
    summary: "WW2 stylized multiplayer FPS sandbox game.",
    developer: "Mohammad Alizade",
    developerId: "Mohammad+Alizade",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.MA.Polyfield",
  },
  "ph.spacedesk.beta": {
    appId: "ph.spacedesk.beta",
    title: "spacedesk",
    summary: "Extend or mirror your PC desktop to Android.",
    developer: "datronicsoft",
    developerId: "datronicsoft",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=ph.spacedesk.beta",
  },
  "hot.fiery.browser": {
    appId: "hot.fiery.browser",
    title: "Fiery Browser",
    summary: "Fast private browser with video download support.",
    developer: "Video Download Studio",
    developerId: "Video+Download+Studio",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=hot.fiery.browser",
  },
  "zombie.survival.craft.z": {
    appId: "zombie.survival.craft.z",
    title: "地球末日：生存",
    summary: "Last Day on Earth zombie survival MMO.",
    developer: "Kefir!",
    developerId: "Kefir!",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=zombie.survival.craft.z",
  },
  "com.glgjing.marvel": {
    appId: "com.glgjing.marvel",
    title: "强力监测",
    summary: "Powerful Android system monitor with widgets.",
    developer: "GLGjing",
    developerId: "GLGjing",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.glgjing.marvel",
  },
  "com.heytap.market": {
    appId: "com.heytap.market",
    title: "OPPO 软件商店",
    summary: "Official OPPO/HeyTap app market.",
    developer: "HeyTap",
    developerId: "HeyTap",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.heytap.market",
  },
  "com.neverland.alreaderext": {
    appId: "com.neverland.alreaderext",
    title: "AlReaderX",
    summary: "E-book reader for fb2, epub, mobi and more.",
    developer: "Alan.Neverland",
    developerId: "Alan.Neverland",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.neverland.alreaderext",
  },
  "eu.darken.sdmmaid": {
    appId: "eu.darken.sdmmaid",
    title: "SD Maid",
    summary: "System cleaning and app management tool for Android.",
    developer: "darken",
    developerId: "darken",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=eu.darken.sdmmaid",
  },
  "org.thoughtcrime.securesms": {
    appId: "org.thoughtcrime.securesms",
    title: "Signal",
    summary: "Private messenger with end-to-end encryption.",
    developer: "Signal Foundation",
    developerId: "Signal+Foundation",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms",
  },
  "jp.pxv.android": {
    appId: "jp.pxv.android",
    title: "pixiv",
    summary: "Illustration and manga community app.",
    developer: "pixiv Inc.",
    developerId: "pixiv+Inc.",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=jp.pxv.android",
  },
  "jp.co.drecom.wizardry.daphne": {
    appId: "jp.co.drecom.wizardry.daphne",
    title: "Wizardry Variants Daphne",
    summary: "3D dungeon exploration RPG from the Wizardry series.",
    developer: "Drecom",
    developerId: "Drecom",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=jp.co.drecom.wizardry.daphne",
  },
  "com.hush.yamby": {
    appId: "com.hush.yamby",
    title: "Yamby",
    summary: "Third-party Emby media client.",
    developer: "YambyOfficial",
    developerId: "YambyOfficial",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.hush.yamby",
  },
  "com.mada.madapay": {
    appId: "com.mada.madapay",
    title: "mada Pay",
    summary: "Digital wallet for mada cards in Saudi Arabia.",
    developer: "mada",
    developerId: "mada",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.mada.madapay",
  },
  "com.avalon.rpg": {
    appId: "com.avalon.rpg",
    title: "Hero of Aethric",
    summary: "Classic turn-based MMORPG.",
    developer: "Northern Forge",
    developerId: "Northern+Forge",
    iconUrl: "",
    playUrl: "https://play.google.com/store/apps/details?id=com.avalon.rpg",
  },
};

export function getCuratedSearchAppMeta(appId: string): CuratedSearchAppMeta | null {
  return CURATED_BY_APP_ID[appId.trim().toLowerCase()] ?? null;
}

export function getKnownAppSearchMeta(appId: string): CuratedSearchAppMeta | null {
  const resolved = resolvePlayPackageIdAlias(appId).trim().toLowerCase();
  const curated = getCuratedSearchAppMeta(resolved);
  if (curated) return curated;

  const displayName = getAliasPackageDisplayName(resolved);
  if (!displayName) return null;

  return {
    appId: resolved,
    title: displayName,
    summary: `Android app (${resolved})`,
    developer: "",
    developerId: "",
    iconUrl: "",
    playUrl: `https://play.google.com/store/apps/details?id=${resolved}`,
  };
}

export function buildMinimalFallbackSearchResult(appId: string) {
  const resolved = resolvePlayPackageIdAlias(appId).trim();
  const playUrl = `https://play.google.com/store/apps/details?id=${resolved}`;
  return {
    appId: resolved,
    title: getAliasPackageDisplayName(resolved) ?? resolved,
    summary: null,
    developer: null,
    developerId: null,
    icon: null,
    score: null,
    scoreText: null,
    priceText: null,
    free: true,
    version: null,
    size: null,
    updated: null,
    url: playUrl,
  };
}

export function buildCuratedSearchResult(meta: CuratedSearchAppMeta) {
  return {
    appId: meta.appId,
    title: meta.title,
    summary: meta.summary,
    developer: meta.developer,
    developerId: meta.developerId,
    icon: proxyImageUrl(meta.iconUrl),
    score: null,
    scoreText: null,
    priceText: null,
    free: true,
    version: null,
    size: null,
    updated: null,
    url: meta.playUrl,
  };
}
