import type { SiteLocale } from "./site-locales";

type DownloadUiStrings = {
  button: string;
  startingIn: (seconds: number) => string;
  almostReady: string;
  started: string;
  preparing: string;
  finalizing: string;
  safe: string;
  checkDownloads: string;
  directRetry: string;
  fallbackPrompt: string;
  fallbackButton: string;
};

const en: DownloadUiStrings = {
  button: "Download APK",
  startingIn: (seconds) => `Starting in ${seconds}s...`,
  almostReady: "Almost ready...",
  started: "Download started",
  preparing: "Fetching the latest APK from our verified source...",
  finalizing: "Just a moment, finalizing your download...",
  safe: "Verified safe to install",
  checkDownloads: "Check your browser's downloads. If it does not start, a backup channel will appear here.",
  directRetry: "If nothing starts, tap here to open the download link.",
  fallbackPrompt: "Download not started? Use the backup channel.",
  fallbackButton: "Use backup download",
};

export const downloadUi: Record<SiteLocale, DownloadUiStrings> = {
  en,
  zh: {
    button: "下载 APK",
    startingIn: (seconds) => `${seconds} 秒后开始...`,
    almostReady: "马上准备好...",
    started: "下载已开始",
    preparing: "正在从已验证来源获取最新 APK...",
    finalizing: "请稍等，正在完成下载准备...",
    safe: "已验证，可安全安装",
    checkDownloads: "请查看浏览器下载列表。如果没有开始下载，备用通道会显示在这里。",
    directRetry: "如果没有开始，请点这里打开下载链接。",
    fallbackPrompt: "下载没有开始？请使用备用通道。",
    fallbackButton: "使用备用下载",
  },
  ja: {
    button: "APK をダウンロード",
    startingIn: (seconds) => `${seconds}秒後に開始...`,
    almostReady: "まもなく準備完了...",
    started: "ダウンロードを開始しました",
    preparing: "確認済みソースから最新 APK を取得しています...",
    finalizing: "少々お待ちください。ダウンロードを準備しています...",
    safe: "安全にインストールできます",
    checkDownloads: "ブラウザのダウンロードを確認してください。開始しない場合、バックアップ経路がここに表示されます。",
    directRetry: "開始しない場合は、ここをタップしてダウンロードリンクを開いてください。",
    fallbackPrompt: "ダウンロードが開始しませんか？バックアップ経路を使用してください。",
    fallbackButton: "バックアップでダウンロード",
  },
  pt: {
    button: "Baixar APK",
    startingIn: (seconds) => `Começa em ${seconds}s...`,
    almostReady: "Quase pronto...",
    started: "Download iniciado",
    preparing: "Buscando o APK mais recente de uma fonte verificada...",
    finalizing: "Só um momento, finalizando o download...",
    safe: "Verificado como seguro para instalar",
    checkDownloads: "Confira os downloads do navegador. Se não iniciar, um canal reserva aparecerá aqui.",
    directRetry: "Se nada começar, toque aqui para abrir o link de download.",
    fallbackPrompt: "O download não começou? Use o canal reserva.",
    fallbackButton: "Usar download reserva",
  },
  es: {
    button: "Descargar APK",
    startingIn: (seconds) => `Comienza en ${seconds}s...`,
    almostReady: "Casi listo...",
    started: "Descarga iniciada",
    preparing: "Obteniendo el APK más reciente desde una fuente verificada...",
    finalizing: "Un momento, finalizando la descarga...",
    safe: "Verificado como seguro para instalar",
    checkDownloads: "Revisa las descargas del navegador. Si no empieza, aparecerá aquí un canal de respaldo.",
    directRetry: "Si no empieza nada, toca aquí para abrir el enlace de descarga.",
    fallbackPrompt: "¿La descarga no empezó? Usa el canal de respaldo.",
    fallbackButton: "Usar descarga de respaldo",
  },
  ru: {
    button: "Скачать APK",
    startingIn: (seconds) => `Начало через ${seconds} с...`,
    almostReady: "Почти готово...",
    started: "Загрузка началась",
    preparing: "Получаем последнюю APK из проверенного источника...",
    finalizing: "Подождите, завершаем подготовку загрузки...",
    safe: "Проверено, безопасно для установки",
    checkDownloads: "Проверьте загрузки браузера. Если загрузка не начнется, здесь появится резервный канал.",
    directRetry: "Если загрузка не началась, нажмите здесь, чтобы открыть ссылку.",
    fallbackPrompt: "Загрузка не началась? Используйте резервный канал.",
    fallbackButton: "Резервная загрузка",
  },
  id: {
    button: "Unduh APK",
    startingIn: (seconds) => `Mulai dalam ${seconds} dtk...`,
    almostReady: "Hampir siap...",
    started: "Unduhan dimulai",
    preparing: "Mengambil APK terbaru dari sumber terverifikasi...",
    finalizing: "Sebentar, menyelesaikan unduhan...",
    safe: "Terverifikasi aman untuk dipasang",
    checkDownloads: "Periksa unduhan browser. Jika belum mulai, saluran cadangan akan muncul di sini.",
    directRetry: "Jika tidak mulai, ketuk di sini untuk membuka tautan unduhan.",
    fallbackPrompt: "Unduhan belum mulai? Gunakan saluran cadangan.",
    fallbackButton: "Gunakan unduhan cadangan",
  },
  hi: {
    button: "APK डाउनलोड करें",
    startingIn: (seconds) => `${seconds} सेकंड में शुरू...`,
    almostReady: "लगभग तैयार...",
    started: "डाउनलोड शुरू हुआ",
    preparing: "सत्यापित स्रोत से नवीनतम APK ला रहे हैं...",
    finalizing: "कृपया प्रतीक्षा करें, डाउनलोड तैयार हो रहा है...",
    safe: "इंस्टॉल करने के लिए सुरक्षित सत्यापित",
    checkDownloads: "ब्राउज़र डाउनलोड देखें। अगर शुरू नहीं होता, तो बैकअप चैनल यहां दिखेगा।",
    directRetry: "अगर कुछ शुरू नहीं होता, डाउनलोड लिंक खोलने के लिए यहां टैप करें।",
    fallbackPrompt: "डाउनलोड शुरू नहीं हुआ? बैकअप चैनल इस्तेमाल करें।",
    fallbackButton: "बैकअप डाउनलोड इस्तेमाल करें",
  },
  ko: {
    button: "APK 다운로드",
    startingIn: (seconds) => `${seconds}초 후 시작...`,
    almostReady: "거의 준비됨...",
    started: "다운로드 시작됨",
    preparing: "검증된 소스에서 최신 APK를 가져오는 중...",
    finalizing: "잠시만요, 다운로드를 마무리하는 중...",
    safe: "설치 안전 확인됨",
    checkDownloads: "브라우저 다운로드를 확인하세요. 시작되지 않으면 백업 채널이 여기에 표시됩니다.",
    directRetry: "시작되지 않으면 여기를 눌러 다운로드 링크를 여세요.",
    fallbackPrompt: "다운로드가 시작되지 않았나요? 백업 채널을 사용하세요.",
    fallbackButton: "백업 다운로드 사용",
  },
  fr: {
    button: "Télécharger l'APK",
    startingIn: (seconds) => `Démarrage dans ${seconds}s...`,
    almostReady: "Presque prêt...",
    started: "Téléchargement lancé",
    preparing: "Récupération du dernier APK depuis une source vérifiée...",
    finalizing: "Un instant, finalisation du téléchargement...",
    safe: "Vérifié comme sûr à installer",
    checkDownloads: "Vérifiez les téléchargements du navigateur. Si rien ne démarre, un canal de secours apparaîtra ici.",
    directRetry: "Si rien ne démarre, touchez ici pour ouvrir le lien de téléchargement.",
    fallbackPrompt: "Le téléchargement n'a pas démarré ? Utilisez le canal de secours.",
    fallbackButton: "Utiliser le téléchargement de secours",
  },
  de: {
    button: "APK herunterladen",
    startingIn: (seconds) => `Start in ${seconds}s...`,
    almostReady: "Fast bereit...",
    started: "Download gestartet",
    preparing: "Lade die neueste APK aus verifizierter Quelle...",
    finalizing: "Einen Moment, Download wird vorbereitet...",
    safe: "Als sicher zur Installation verifiziert",
    checkDownloads: "Prüfen Sie die Browser-Downloads. Falls nichts startet, erscheint hier ein Backup-Kanal.",
    directRetry: "Wenn nichts startet, tippen Sie hier, um den Download-Link zu öffnen.",
    fallbackPrompt: "Download nicht gestartet? Nutzen Sie den Backup-Kanal.",
    fallbackButton: "Backup-Download nutzen",
  },
  vi: {
    button: "Tải APK",
    startingIn: (seconds) => `Bắt đầu sau ${seconds}s...`,
    almostReady: "Gần xong...",
    started: "Đã bắt đầu tải xuống",
    preparing: "Đang lấy APK mới nhất từ nguồn đã xác minh...",
    finalizing: "Vui lòng chờ, đang hoàn tất tải xuống...",
    safe: "Đã xác minh an toàn để cài đặt",
    checkDownloads: "Kiểm tra mục tải xuống của trình duyệt. Nếu chưa bắt đầu, kênh dự phòng sẽ xuất hiện ở đây.",
    directRetry: "Nếu chưa bắt đầu, hãy nhấn vào đây để mở liên kết tải xuống.",
    fallbackPrompt: "Tải xuống chưa bắt đầu? Hãy dùng kênh dự phòng.",
    fallbackButton: "Dùng tải xuống dự phòng",
  },
  ar: {
    button: "تنزيل APK",
    startingIn: (seconds) => `سيبدأ خلال ${seconds} ث...`,
    almostReady: "جاهز تقريبًا...",
    started: "بدأ التنزيل",
    preparing: "جارٍ جلب أحدث APK من مصدر موثوق...",
    finalizing: "لحظة من فضلك، جارٍ إنهاء التنزيل...",
    safe: "تم التحقق من أنه آمن للتثبيت",
    checkDownloads: "تحقق من تنزيلات المتصفح. إذا لم يبدأ التنزيل، سيظهر مسار احتياطي هنا.",
    directRetry: "إذا لم يبدأ شيء، اضغط هنا لفتح رابط التنزيل.",
    fallbackPrompt: "لم يبدأ التنزيل؟ استخدم المسار الاحتياطي.",
    fallbackButton: "استخدام التنزيل الاحتياطي",
  },
  tr: {
    button: "APK indir",
    startingIn: (seconds) => `${seconds} sn içinde başlıyor...`,
    almostReady: "Neredeyse hazır...",
    started: "İndirme başladı",
    preparing: "Doğrulanmış kaynaktan en yeni APK alınıyor...",
    finalizing: "Bir an, indirme sonlandırılıyor...",
    safe: "Kurulum için güvenli olduğu doğrulandı",
    checkDownloads: "Tarayıcı indirmelerini kontrol edin. Başlamazsa yedek kanal burada görünecek.",
    directRetry: "Hiçbir şey başlamazsa indirme bağlantısını açmak için buraya dokunun.",
    fallbackPrompt: "İndirme başlamadı mı? Yedek kanalı kullanın.",
    fallbackButton: "Yedek indirmeyi kullan",
  },
  it: {
    button: "Scarica APK",
    startingIn: (seconds) => `Avvio tra ${seconds}s...`,
    almostReady: "Quasi pronto...",
    started: "Download avviato",
    preparing: "Recupero dell'APK più recente da una fonte verificata...",
    finalizing: "Un momento, finalizzazione del download...",
    safe: "Verificato come sicuro da installare",
    checkDownloads: "Controlla i download del browser. Se non parte, qui apparirà un canale di backup.",
    directRetry: "Se non parte nulla, tocca qui per aprire il link di download.",
    fallbackPrompt: "Download non avviato? Usa il canale di backup.",
    fallbackButton: "Usa download di backup",
  },
  nl: {
    button: "APK downloaden",
    startingIn: (seconds) => `Start over ${seconds}s...`,
    almostReady: "Bijna klaar...",
    started: "Download gestart",
    preparing: "Nieuwste APK ophalen uit geverifieerde bron...",
    finalizing: "Even geduld, download afronden...",
    safe: "Geverifieerd veilig om te installeren",
    checkDownloads: "Controleer de downloads van je browser. Als het niet start, verschijnt hier een back-upkanaal.",
    directRetry: "Als er niets start, tik hier om de downloadlink te openen.",
    fallbackPrompt: "Download niet gestart? Gebruik het back-upkanaal.",
    fallbackButton: "Back-updownload gebruiken",
  },
  pl: {
    button: "Pobierz APK",
    startingIn: (seconds) => `Start za ${seconds}s...`,
    almostReady: "Prawie gotowe...",
    started: "Pobieranie rozpoczęte",
    preparing: "Pobieranie najnowszego APK ze zweryfikowanego źródła...",
    finalizing: "Chwileczkę, finalizujemy pobieranie...",
    safe: "Zweryfikowano jako bezpieczne do instalacji",
    checkDownloads: "Sprawdź pobrane pliki w przeglądarce. Jeśli nie ruszy, pojawi się tu kanał zapasowy.",
    directRetry: "Jeśli nic się nie zacznie, stuknij tutaj, aby otworzyć link pobierania.",
    fallbackPrompt: "Pobieranie nie ruszyło? Użyj kanału zapasowego.",
    fallbackButton: "Użyj pobierania zapasowego",
  },
  uk: {
    button: "Завантажити APK",
    startingIn: (seconds) => `Початок через ${seconds} с...`,
    almostReady: "Майже готово...",
    started: "Завантаження почалося",
    preparing: "Отримуємо останній APK з перевіреного джерела...",
    finalizing: "Зачекайте, завершуємо підготовку завантаження...",
    safe: "Перевірено, безпечно для встановлення",
    checkDownloads: "Перевірте завантаження браузера. Якщо не почнеться, тут з'явиться резервний канал.",
    directRetry: "Якщо нічого не почалося, натисніть тут, щоб відкрити посилання.",
    fallbackPrompt: "Завантаження не почалося? Скористайтеся резервним каналом.",
    fallbackButton: "Використати резервне завантаження",
  },
  th: {
    button: "ดาวน์โหลด APK",
    startingIn: (seconds) => `เริ่มใน ${seconds} วินาที...`,
    almostReady: "เกือบพร้อมแล้ว...",
    started: "เริ่มดาวน์โหลดแล้ว",
    preparing: "กำลังดึง APK ล่าสุดจากแหล่งที่ตรวจสอบแล้ว...",
    finalizing: "โปรดรอสักครู่ กำลังเตรียมการดาวน์โหลด...",
    safe: "ตรวจสอบแล้วว่าปลอดภัยสำหรับการติดตั้ง",
    checkDownloads: "ตรวจสอบรายการดาวน์โหลดของเบราว์เซอร์ หากยังไม่เริ่ม ช่องทางสำรองจะแสดงที่นี่",
    directRetry: "หากยังไม่เริ่ม ให้แตะที่นี่เพื่อเปิดลิงก์ดาวน์โหลด",
    fallbackPrompt: "ดาวน์โหลดไม่เริ่ม? ใช้ช่องทางสำรอง",
    fallbackButton: "ใช้การดาวน์โหลดสำรอง",
  },
  ms: {
    button: "Muat turun APK",
    startingIn: (seconds) => `Bermula dalam ${seconds}s...`,
    almostReady: "Hampir siap...",
    started: "Muat turun bermula",
    preparing: "Mengambil APK terkini daripada sumber yang disahkan...",
    finalizing: "Sebentar, memuktamadkan muat turun...",
    safe: "Disahkan selamat untuk dipasang",
    checkDownloads: "Semak muat turun pelayar. Jika tidak bermula, saluran sandaran akan muncul di sini.",
    directRetry: "Jika tiada apa-apa bermula, ketik di sini untuk membuka pautan muat turun.",
    fallbackPrompt: "Muat turun belum bermula? Gunakan saluran sandaran.",
    fallbackButton: "Guna muat turun sandaran",
  },
  sv: {
    button: "Ladda ner APK",
    startingIn: (seconds) => `Startar om ${seconds}s...`,
    almostReady: "Nästan klart...",
    started: "Nedladdning startad",
    preparing: "Hämtar senaste APK från verifierad källa...",
    finalizing: "Ett ögonblick, slutför nedladdningen...",
    safe: "Verifierad som säker att installera",
    checkDownloads: "Kontrollera webbläsarens nedladdningar. Om det inte startar visas en reservkanal här.",
    directRetry: "Om inget startar, tryck här för att öppna nedladdningslänken.",
    fallbackPrompt: "Startade inte nedladdningen? Använd reservkanalen.",
    fallbackButton: "Använd reservnedladdning",
  },
  da: {
    button: "Download APK",
    startingIn: (seconds) => `Starter om ${seconds}s...`,
    almostReady: "Næsten klar...",
    started: "Download startet",
    preparing: "Henter den nyeste APK fra en verificeret kilde...",
    finalizing: "Et øjeblik, download færdiggøres...",
    safe: "Bekræftet sikker at installere",
    checkDownloads: "Tjek browserens downloads. Hvis den ikke starter, vises en backup-kanal her.",
    directRetry: "Hvis intet starter, tryk her for at åbne downloadlinket.",
    fallbackPrompt: "Download ikke startet? Brug backup-kanalen.",
    fallbackButton: "Brug backup-download",
  },
  fi: {
    button: "Lataa APK",
    startingIn: (seconds) => `Alkaa ${seconds} s kuluttua...`,
    almostReady: "Melkein valmis...",
    started: "Lataus aloitettu",
    preparing: "Haetaan uusinta APK:ta vahvistetusta lähteestä...",
    finalizing: "Hetki, viimeistellään latausta...",
    safe: "Vahvistettu turvalliseksi asentaa",
    checkDownloads: "Tarkista selaimen lataukset. Jos lataus ei ala, varakanava ilmestyy tähän.",
    directRetry: "Jos mitään ei ala, avaa latauslinkki napauttamalla tästä.",
    fallbackPrompt: "Lataus ei alkanut? Käytä varakanavaa.",
    fallbackButton: "Käytä varalatausta",
  },
  nb: {
    button: "Last ned APK",
    startingIn: (seconds) => `Starter om ${seconds}s...`,
    almostReady: "Nesten klar...",
    started: "Nedlasting startet",
    preparing: "Henter nyeste APK fra verifisert kilde...",
    finalizing: "Et øyeblikk, fullfører nedlastingen...",
    safe: "Bekreftet trygg å installere",
    checkDownloads: "Sjekk nedlastingene i nettleseren. Hvis den ikke starter, vises en reservekanal her.",
    directRetry: "Hvis ingenting starter, trykk her for å åpne nedlastingslenken.",
    fallbackPrompt: "Nedlastingen startet ikke? Bruk reservekanalen.",
    fallbackButton: "Bruk reservenedlasting",
  },
  cs: {
    button: "Stáhnout APK",
    startingIn: (seconds) => `Začíná za ${seconds} s...`,
    almostReady: "Téměř připraveno...",
    started: "Stahování spuštěno",
    preparing: "Získávání nejnovější APK z ověřeného zdroje...",
    finalizing: "Chvíli strpení, dokončujeme stahování...",
    safe: "Ověřeno jako bezpečné k instalaci",
    checkDownloads: "Zkontrolujte stažené soubory v prohlížeči. Pokud nezačne, zobrazí se zde záložní kanál.",
    directRetry: "Pokud nic nezačne, klepnutím sem otevřete odkaz ke stažení.",
    fallbackPrompt: "Stahování nezačalo? Použijte záložní kanál.",
    fallbackButton: "Použít záložní stahování",
  },
  ro: {
    button: "Descarcă APK",
    startingIn: (seconds) => `Începe în ${seconds}s...`,
    almostReady: "Aproape gata...",
    started: "Descărcarea a început",
    preparing: "Se preia cel mai nou APK dintr-o sursă verificată...",
    finalizing: "Un moment, finalizăm descărcarea...",
    safe: "Verificat ca sigur pentru instalare",
    checkDownloads: "Verifică descărcările browserului. Dacă nu pornește, canalul de rezervă va apărea aici.",
    directRetry: "Dacă nu pornește nimic, atinge aici pentru a deschide linkul de descărcare.",
    fallbackPrompt: "Descărcarea nu a pornit? Folosește canalul de rezervă.",
    fallbackButton: "Folosește descărcarea de rezervă",
  },
  el: {
    button: "Λήψη APK",
    startingIn: (seconds) => `Ξεκινά σε ${seconds}s...`,
    almostReady: "Σχεδόν έτοιμο...",
    started: "Η λήψη ξεκίνησε",
    preparing: "Λήψη του νεότερου APK από επαληθευμένη πηγή...",
    finalizing: "Ένα λεπτό, ολοκληρώνεται η λήψη...",
    safe: "Επαληθεύτηκε ως ασφαλές για εγκατάσταση",
    checkDownloads: "Ελέγξτε τις λήψεις του προγράμματος περιήγησης. Αν δεν ξεκινήσει, θα εμφανιστεί εδώ εφεδρικό κανάλι.",
    directRetry: "Αν δεν ξεκινήσει τίποτα, πατήστε εδώ για να ανοίξετε τον σύνδεσμο λήψης.",
    fallbackPrompt: "Η λήψη δεν ξεκίνησε; Χρησιμοποιήστε το εφεδρικό κανάλι.",
    fallbackButton: "Χρήση εφεδρικής λήψης",
  },
  hu: {
    button: "APK letöltése",
    startingIn: (seconds) => `Indul ${seconds} mp múlva...`,
    almostReady: "Majdnem kész...",
    started: "Letöltés elindult",
    preparing: "A legújabb APK lekérése ellenőrzött forrásból...",
    finalizing: "Egy pillanat, a letöltés véglegesítése...",
    safe: "Telepítésre biztonságosnak ellenőrizve",
    checkDownloads: "Ellenőrizd a böngésző letöltéseit. Ha nem indul el, itt megjelenik egy tartalék csatorna.",
    directRetry: "Ha semmi nem indul el, koppints ide a letöltési link megnyitásához.",
    fallbackPrompt: "Nem indult el a letöltés? Használd a tartalék csatornát.",
    fallbackButton: "Tartalék letöltés használata",
  },
  bn: {
    button: "APK ডাউনলোড করুন",
    startingIn: (seconds) => `${seconds} সেকেন্ডে শুরু...`,
    almostReady: "প্রায় প্রস্তুত...",
    started: "ডাউনলোড শুরু হয়েছে",
    preparing: "যাচাইকৃত উৎস থেকে সর্বশেষ APK আনা হচ্ছে...",
    finalizing: "একটু অপেক্ষা করুন, ডাউনলোড প্রস্তুত হচ্ছে...",
    safe: "ইনস্টলের জন্য নিরাপদ যাচাই করা হয়েছে",
    checkDownloads: "ব্রাউজারের ডাউনলোড দেখুন। শুরু না হলে ব্যাকআপ চ্যানেল এখানে দেখাবে।",
    directRetry: "কিছু শুরু না হলে, ডাউনলোড লিঙ্ক খুলতে এখানে ট্যাপ করুন।",
    fallbackPrompt: "ডাউনলোড শুরু হয়নি? ব্যাকআপ চ্যানেল ব্যবহার করুন।",
    fallbackButton: "ব্যাকআপ ডাউনলোড ব্যবহার করুন",
  },
  tl: {
    button: "I-download APK",
    startingIn: (seconds) => `Magsisimula sa ${seconds}s...`,
    almostReady: "Halos handa na...",
    started: "Nagsimula na ang download",
    preparing: "Kinukuha ang pinakabagong APK mula sa na-verify na source...",
    finalizing: "Sandali lang, tinatapos ang download...",
    safe: "Na-verify na ligtas i-install",
    checkDownloads: "Tingnan ang downloads ng browser. Kung hindi magsimula, lalabas dito ang backup channel.",
    directRetry: "Kung walang nagsimula, i-tap dito para buksan ang download link.",
    fallbackPrompt: "Hindi nagsimula ang download? Gamitin ang backup channel.",
    fallbackButton: "Gamitin ang backup download",
  },
  he: {
    button: "הורדת APK",
    startingIn: (seconds) => `מתחיל בעוד ${seconds} שניות...`,
    almostReady: "כמעט מוכן...",
    started: "ההורדה התחילה",
    preparing: "מקבל את ה-APK האחרון ממקור מאומת...",
    finalizing: "רגע, מסיים את ההורדה...",
    safe: "אומת כבטוח להתקנה",
    checkDownloads: "בדוק את הורדות הדפדפן. אם זה לא מתחיל, ערוץ גיבוי יופיע כאן.",
    directRetry: "אם שום דבר לא מתחיל, הקש כאן כדי לפתוח את קישור ההורדה.",
    fallbackPrompt: "ההורדה לא התחילה? השתמש בערוץ הגיבוי.",
    fallbackButton: "השתמש בהורדת גיבוי",
  },
  fa: {
    button: "دانلود APK",
    startingIn: (seconds) => `شروع تا ${seconds} ثانیه...`,
    almostReady: "تقریباً آماده است...",
    started: "دانلود شروع شد",
    preparing: "در حال دریافت آخرین APK از منبع تأییدشده...",
    finalizing: "چند لحظه صبر کنید، دانلود نهایی می‌شود...",
    safe: "برای نصب ایمن تأیید شده است",
    checkDownloads: "دانلودهای مرورگر را بررسی کنید. اگر شروع نشد، مسیر پشتیبان اینجا نمایش داده می‌شود.",
    directRetry: "اگر چیزی شروع نشد، برای باز کردن لینک دانلود اینجا بزنید.",
    fallbackPrompt: "دانلود شروع نشد؟ از مسیر پشتیبان استفاده کنید.",
    fallbackButton: "استفاده از دانلود پشتیبان",
  },
  ur: {
    button: "APK ڈاؤن لوڈ کریں",
    startingIn: (seconds) => `${seconds} سیکنڈ میں شروع...`,
    almostReady: "تقریباً تیار...",
    started: "ڈاؤن لوڈ شروع ہو گیا",
    preparing: "تصدیق شدہ ذریعہ سے تازہ ترین APK حاصل کیا جا رہا ہے...",
    finalizing: "ایک لمحہ، ڈاؤن لوڈ مکمل کیا جا رہا ہے...",
    safe: "انسٹال کرنے کے لیے محفوظ تصدیق شدہ",
    checkDownloads: "براؤزر کے ڈاؤن لوڈز چیک کریں۔ اگر شروع نہ ہو تو بیک اپ چینل یہاں ظاہر ہوگا۔",
    directRetry: "اگر کچھ شروع نہ ہو تو ڈاؤن لوڈ لنک کھولنے کے لیے یہاں ٹیپ کریں۔",
    fallbackPrompt: "ڈاؤن لوڈ شروع نہیں ہوا؟ بیک اپ چینل استعمال کریں۔",
    fallbackButton: "بیک اپ ڈاؤن لوڈ استعمال کریں",
  },
};
